"""Core data models for the DMHY anime subscription workflow."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import StrEnum
from typing import Any


class DownloadJobStatus(StrEnum):
    """Lifecycle states tracked for submitted downloads."""

    PENDING = "pending"
    SUBMITTED = "submitted"
    QUEUED = "queued"
    DOWNLOADING = "downloading"
    STALLED = "stalled"
    ERROR = "error"
    MISSING = "missing"
    DELETED = "deleted"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


class OrganizerMode(StrEnum):
    """Organizer execution mode from configuration."""

    DRY_RUN = "dry-run"
    APPLY = "apply"
    MOVE = "move"


class RuleEpisodeMode(StrEnum):
    """Feed item shapes accepted by a subscription rule."""

    EPISODE = "episode"
    PACK = "pack"
    BOTH = "both"


@dataclass(frozen=True, slots=True)
class FeedItem:
    """Raw release data discovered from a feed."""

    title: str
    link: str
    published_at: datetime | None = None
    guid: str | None = None
    info_hash: str | None = None
    magnet_uri: str | None = None
    torrent_url: str | None = None
    normalized_title: str | None = None
    source_feed: str | None = None
    description: str | None = None
    author: str | None = None
    category: str | None = None
    is_season_pack: bool = False

    @property
    def dedupe_key(self) -> str:
        """Return the future dedupe hierarchy: infohash, guid, then title/date."""

        if self.info_hash:
            return f"infohash:{self.info_hash.lower()}"
        if self.guid:
            return f"guid:{self.guid}"
        title = self.normalized_title or self.title.strip().casefold()
        published = self.published_at.isoformat() if self.published_at else "unknown-date"
        return f"title-date:{title}:{published}"


@dataclass(frozen=True, slots=True)
class ReleaseCandidate:
    """A feed item matched to one subscription rule."""

    feed_item: FeedItem
    rule_name: str
    title: str
    episode: str | None = None
    season: str | None = None
    quality: str | None = None
    priority: int = 0
    reason: str | None = None


@dataclass(frozen=True, slots=True)
class SubscriptionRule:
    """Declarative matching rule loaded from configuration."""

    name: str
    include_keywords: tuple[str, ...] = ()
    exclude_keywords: tuple[str, ...] = ()
    use_regex: bool = False
    team_names: tuple[str, ...] = ()
    resolutions: tuple[str, ...] = ()
    categories: tuple[str, ...] = ()
    episode_mode: RuleEpisodeMode = RuleEpisodeMode.EPISODE
    allow_packs: bool = False
    feed_names: tuple[str, ...] = ()
    save_path: str | None = None
    category: str | None = None
    bangumi_subject_id: int | None = None
    priority: int = 0
    enabled: bool = True


@dataclass(frozen=True, slots=True)
class DownloadJob:
    """Stateful download request created from a release candidate."""

    job_id: str
    candidate: ReleaseCandidate
    status: DownloadJobStatus = DownloadJobStatus.PENDING
    torrent_hash: str | None = None
    retry_count: int = 0
    last_error: str | None = None
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass(frozen=True, slots=True)
class LibraryMovePlan:
    """Planned organizer action without performing file moves."""

    source_path: str
    destination_path: str
    mode: OrganizerMode
    job_id: str | None = None
    should_apply: bool = False


@dataclass(frozen=True, slots=True)
class NotificationEvent:
    """Webhook-ready event payload generated by workflow stages."""

    event_type: str
    title: str
    message: str
    job_id: str | None = None
    severity: str = "info"
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass(frozen=True, slots=True)
class FailureRecord:
    """Failure and retry bookkeeping for a workflow item."""

    subject_id: str
    stage: str
    message: str
    attempts: int
    last_failed_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    recoverable: bool = True


@dataclass(frozen=True, slots=True)
class StateEntry:
    """Durable state row for seen items, jobs, and organizer outcomes."""

    key: str
    kind: str
    payload: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
